name: 'Build Pull Request'
run-name: Build and upload preview for PR ${{ github.event.pull_request.number }}

on:
  pull_request:
    types: [synchronize, opened]

jobs:
  build:
    name: Build and upload site
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm install
      - name: Build website
        run: npm run build

      - uses: actions/checkout@v4
        with:
          path: website
          submodules: recursive
          repository: neoforged/websites

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: latest

      - name: Copy files
        run: |
          cp dist/mod-generator.js website/assets/js/mod-generator.js
          cp dist/mod-generator.css website/assets/js/mod-generator.css

      - name: Generate layout
        with:
          FILE: |
            {{ define "main" }}
            <main class="main list" role="main">
                <h1>NeoForge Testing Mod Generator</h1>

                <p>
                    This page is based on mod-generator <a href="https://github.com/neoforged/mod-generator/pull/${{ github.event.pull_request.number }}">PR #${{ github.event.pull_request.number }}</a>
                </p>

                <div id="mod-generator-app"></div>
                <script type="module" src="/js/mod-generator.js"></script>
                <link rel="stylesheet" href="/css/mod-generator.css" />
            </main>
            {{ end }}
        run: |
          rm website/layouts/page/mod-generator.html
          echo "$FILE" >> website/layouts/page/mod-generator.html

      - name: Build
        run: |
          cd website
          hugo -F

      - uses: matyrobbrt/cloudflare-pr-previews/upload@v1
        name: Upload website
        with:
          build-dir: ./website/public
